### PR TITLE
Support CSS Color Names, Values, and Keywords

### PR DESCRIPTION
**Pull request by javacraft**
The current Color class implementation is too restrictive and only supports CSS color values (e.g. `#45004A`). This contribution adds the following:

* Relaxes color value checks. Color values, names, and keywords are saved as is in lowercase to normalize values.
* Color supports keywords such as `transparent` (this drove the release of this update) and others as  they are specified in W3C's [CSS Color Module Level 3 Specification](https://www.w3.org/TR/css-color-3/) or future versions.
* Unit tests have been updated to use new Color class and slightly streamlined (i.e. declaring test colors as static elements for reuse by all tests.
* Unit test artifacts are now created under `target/` outside the scope of revision control.
* `.gitignore` has been updated to handle most common local IDE artifacts.

Best regards,
frelling

### CODE REVIEW

**Comment by miachm** [comment]
Hi! Thanks for your contribution!

It has good changes (gitignore, documentation, tests style...) but unfortunately there is a problem with the main commit.

Error checks are restrictive because ODS colors are restrictive:

> The values of the fo:background-color attribute are transparent or a value of type color 18.3.9.
> -------
> 18.3.9
> A RGB color in conformance with §5.9.11 of [XSL], that is a RGB color in notation “#rrggbb”, where rr, gg and bb are 8-bit hexadecimal digits.

http://docs.oasis-open.org/office/v1.2/cs01/OpenDocument-v1.2-cs01-part1.html#datatype-color
http://docs.oasis-open.org/office/v1.2/cs01/OpenDocument-v1.2-cs01-part1.html#__RefHeading__1419778_253892949

So, you can't use "red" and expect it to work. You can't even use "#f00", it has to be exactly 7 letters.

"Transparent" is a corner case which we should take care, but that's not the right way.

**Comment by javacraft** [comment]
Sorry for the delay in replying. I wound up having to take a deep dive into `odftoolkit` for the past week to achieve the end results; such as styling and formatting table entries automatically to save hours of manual formatting whenever "non-developers" needs a formatted report. That is not to say that I have stopped using SODS; it is far more convenient when it comes to pushing or pulling data from a spreadsheet. 

I came to realize that #0f0 or color names did not work even with `odftoolkit` even though it happily allowed me to do so. I came across ISO/IEC 26300-1, Section 18.3.9, shortly thereafter. Go figure that XSL only uses a subset of the W3C color specification. I am certain there was probably a good reason, I think they wanted data to be in its "purest" form, but that is just a conjecture. 

However, except for changing the reference of W3C color to XSL spec in the Color class comments, the changes are still valid.

Ask yourself,
* Is it the responsibility of SODS to apply validations to what essentially is user data? 
* Is it the responsibility of SODS to also validate formulas ensuring they conform to ISO/IEC 26300-2 (Recalculated Formula Format)?
* Is it the responsibility of SODS to protect data from the user?

I mean no ill, but this is not the first or the last time I will come across a "color" class variant created by exuberant developers; after all, it is by far one of the more perfect entities that fits snugly into an object-oriented paradigm. Hence, the ability to set and get R, G, and B values and other "fluff". 

How about we keep it simple -- a container to hold a color specification -- without holding the hands of the user.

I recommend you accept the PR, but then tweak the comments on the Color class stating that its values follows XSL-specs; however, that no data validation is performed. If not, then pick and choice whatever other changes I have suggested. Add then as your own; credit on my behalf is the least of my concerns.

**Comment by PawelSkwaraEuvic** [comment]
Perhaps for transparency edge case it's enough to add simple if condition no to set color in this case and leave it as null. It's only a guess i'm not too deep in ods structure.

**Comment by miachm** [comment]
Sorry for the delay, i have been busy the last two weeks.

Yes, SODS needs a lot of work about formatting. The roadmap is going in that direction, conditional formating shouldn't be hard anyway.

> Is it the responsibility of SODS to apply validations to what essentially is user data?

I think i am gonna use a middle ground.

I am gonna ignore color errors while reading ODS files, because i understand it is an inconvenience for the programmer since it's outside his control. After all, LibreOffice doesn't crash if the cell's color has an invalid format.

But colors defined by the programmer should be validated. The programmer need to trust that the library is gonna do what he said (fail-fast principle).

Your case is a good example, you didn't know that you need to use a XSL-SPEC. So you would be using colors like "blue" or "#cef" without noticing anything. Nobody reads the documentation until it's late.

> Is it the responsibility of SODS to also validate formulas ensuring they conform to ISO/IEC 26300-2 (Recalculated Formula Format)?

I would like to but i know that it's not realistic.

Nevertheless, programmers doesn't know that standard. So the probability of confusion is minor.

> Is it the responsibility of SODS to protect data from the user?

SODS use the fail-fast principle. If an operation is accepted by SODS, you can be sure that it will work successfully.

There are some caveats (formulas), but the library tries to use this principle when it's possible.

------

I did a merge with the gitignore and tests changed. Thanks!

**Pull request merged**
